# Generated by Django 3.1.4 on 2021-02-17 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20210217_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('plaid_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='direction',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='budgeting.wallet'),
        ),
    ]
