# Generated by Django 3.1.4 on 2021-02-18 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20210217_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
