# Generated by Django 3.1.4 on 2021-02-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_auto_20210219_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_categories', to='budgeting.categorygroup'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='budgeting.category'),
        ),
    ]
