# Generated by Django 3.1.4 on 2021-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_auto_20210219_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
