# Generated by Django 3.1.4 on 2021-02-22 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0008_categorygroup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('wallet_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_import',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
