# Generated by Django 3.1.4 on 2021-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0009_auto_20210222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='error_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
