# Generated by Django 3.1.4 on 2021-02-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0010_auto_20210222_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
