# Generated by Django 3.1.4 on 2021-02-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0011_auto_20210223_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
