# Generated by Django 3.1.4 on 2021-03-01 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0014_auto_20210225_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('task', models.CharField(choices=[('first_import_transaction_notification', 'First import transaction notification')], max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('obj_id', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
