# Generated by Django 3.1.4 on 2021-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0015_tasknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknote',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='obj_id',
            field=models.IntegerField(null=True),
        ),
    ]
