# Generated by Django 3.1.4 on 2021-03-15 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0016_auto_20210301_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='task',
            field=models.CharField(choices=[('first_import_transaction_notification', 'First import transaction notification'), ('over_budget_notification', 'over_budget_notification')], max_length=255),
        ),
    ]
